### ISSUE TITLE
Confirmation of Python version

### ISSUE THREAD

**Issue by andrewtarzia** [maccallumlab/martini_openmm#16]
Hey all, thank you for the very useful code!

I am working on a software that requires Python 3.11, and have downloaded and tested your software in that environment with no failures. (also using `GROMACS version:    2021.4-Ubuntu-2021.4-2`).

Are there are any other checks I should run to check compatability?

**Comment by andrewtarzia** [comment]
Also using `OpenMM                        8.0.0`

**Comment by jlmaccal** [comment]
I don't foresee any challenges with Python 3.11, as I don't think they've made any backwards incompatible changes.

For OpenMM 8.0.0, as long as the plugin compiles, everything should work fine. We need to update our packages at some point.

**Comment by andrewtarzia** [comment]
Excellent, thank you!

When you say 'if the plugin compiles', is there a direct way to test that?

**Comment by jlmaccal** [comment]
Ah, sorry... I was thinking of the wrong project.

If you are successfully able to run a simple simulation, that's a strong indication that everything is working. You could also run the test suite, but that requires a gromacs installation and takes a bit of time to complete.

**Comment by andrewtarzia** [comment]
Ahh perfect, I ran the tests with Gromacs and they all passed. So I will trust it is fine for now!
