### ISSUE TITLE
Did any progress for martini 3 force field?

### ISSUE THREAD

**Issue by Byun-jinyoung** [maccallumlab/martini_openmm#2]
Dear readers,
I was a bit new in openMM. Recently I've used the martini v3 force field for my project.
I want to use and accelerate the martini v3 force field by using OpenMM package, followed by comparing the martini v3 result with martini v2.2 result. 
Is there any plan for supporting the martini 3 force field?

Thank you :)

**Comment by jlmaccal** [comment]
The `martini3` branch has a mostly complete implementation of Martini 3.

There are still a few things left to implement, but many systems should work already.

**Comment by Byun-jinyoung** [comment]
Is it recommended that I used the `martini3` branch? I've already used the martini_openmm code in `martini` branch. Dose the codes in `martini3` branch support both martini v2.2 and martini v3 force fields?

**Comment by Byun-jinyoung** [comment]
@jlmaccal 
Can you give me simple comments about the difference of implementation in martini_openmm between `martini v2` and `martini v3`?

**Comment by jlmaccal** [comment]
I would recommend using the `martini3` branch. It implements all of martini2 and most of martini3. If your system uses one of the functional forms that is not implemented, you will get an error. Our plan is to support all of martini3, but we are still assembling test cases to cover all of the different functional forms for bonded types.
