### ISSUE TITLE
recommended branch?

### ISSUE THREAD

**Issue by agrossfield** [maccallumlab/martini_openmm#6]
Hi all,

We're thinking of playing with your martini implementation. We'll be using martini 2, since as far as I can tell there still isn't an official martini 3 cholesterol (though apparently they're available if you ask one of the devs). Which branch do you currently recommend we use?

Thanks,

Alan

**Comment by jlmaccal** [comment]
The `martini3` branch is the one being actively developed and tested. Despite the name, it's actually a martini 2 implementation as well. I would suggest using that one. We will likely merge that into master in the next week or two anyway.

Note, there are some problems with the Martini 2 cholesterol topology in OpenMM. We're working on an alternative topology, see `openmm_CHOL.it[` in the `cholesterol` folder.
